baseURL = "https://mdesani.github.io/jubilant-tummy"
languageCode = "en-us"
title = "Jubilant Tummy"
theme = "minimal"

[params]
    author = "Megha Shah Desani"
    description = "My home-cooking food and recipe blogs"
    accent = "purple"
    showBorder = true
    backgroundColor = "white"
    font = "Roboto" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 3

[[menu.icon]]
    url = "mailto:megha.shah@outlook.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/mdesani/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/MeghaShahDesani/"
    name = "twitter"
    weight = 3
